# Site settings
title: Akshat Aggarwal
description: "Welcome to Akshat's Corner!"
url: 'https://akshat7.github.io/jekyll-uno/'
baseurl: '/jekyll-uno/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Akshat Aggarwal'
  email: akshat16.agr@gmail.com
  twitter_username: joshgerdes
  facebook_username: akshat7
  github_username:  akshat7
  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
